name: wakelock_windows
description: >2-
  Windows platform implementation of the wakelock_platform_interface for the wakelock plugin.
version: 0.2.1
repository: https://github.com/sasen98/wakelock/tree/versionup/wakelock_windows

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  wakelock_platform_interface:
    git:
      url: https://github.com/sasen98/wakelock
      path: wakelock_platform_interface
      ref: versionup

  win32: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
# todo: use dartPluginClass declaration once that lands on stable (https://github.com/flutter/flutter/issues/52267_
#flutter:
#  plugin:
#    platforms:
#      windows:
#        dartPluginClass: WakelockWindows
