name: wakelock_web
description: Web platform implementation of the wakelock_platform_interface for the wakelock plugin.
version: 0.4.0
repository: https://github.com/creativecreatorormaybenot/wakelock/tree/main/wakelock_web

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.24.0-0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  js: ^0.7.1

  wakelock_platform_interface:
    git:
      url: https://github.com/sasen98/wakelock
      path: wakelock_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  wakelock:
    path: ../wakelock

flutter:
  plugin:
    platforms:
      web:
        pluginClass: WakelockWeb
        fileName: wakelock_web.dart

  assets:
    - assets/no_sleep.js
