name: wakelock_macos
description: >2-
  macOS platform implementation of the wakelock_platform_interface for the wakelock plugin.
version: 0.4.0
repository: https://github.com/sasen98/wakelock/tree/versionup/wakelock_macos

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  wakelock_platform_interface:
    git:
      url: https://github.com/sasen98/wakelock
      path: wakelock_platform_interface
      ref: versionup

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: WakelockMacosPlugin
        fileName: wakelock_macos.dart
